### ISSUE TITLE
Refinement: Ontology selector

### ISSUE THREAD

**Issue by mbaudis** [progenetix/progenetix-web#11]
The ontology selector (i.e. the most relevant metadata filter) is pre-populated with values from all datasets, which are themselves filtered by an optional `filters` value (e.g. a prefix).

The `useFilteringTerms` call should be executed again upon selecting one or several `datasetIds`, to reflect the correct content (i.e. represented filters) and counts.

**Comment by ptoussai** [comment]
I improved the selector UX by making it searchable. This is unrelated to the solution presented here.
To implement this solution I would need the backend to return the filters associated to the `datasetIds`.

**Comment by mbaudis** [comment]
Not checked the current status due to "offline" mode, but adding e.g. `&datasetIds=arraymap` etc. should work.

**Comment by ptoussai** [comment]
It seems to work fine.
