### ISSUE TITLE
Display of additional handovers

### ISSUE THREAD

**Issue by mbaudis** [progenetix/progenetix-web#19]
The links / empty (“not implemented”) tabs in the panel are distracting; the display itself obfuscates the h->o mechanism and provides direct functionality; that h->o is behind is irrelevant from the user”s POV. A better way would be to remove these and to have a "show handovers" interface in which links/labels are provided for all.

**Comment by ptoussai** [comment]
Fix in the latest push.
I simply added the links to the box.
If ok, please close it.
