### ISSUE TITLE
Sample search: request types and defaults

### ISSUE THREAD

**Issue by ptoussai** [progenetix/progenetix-web#26]
At the moment the sample search uses the same mechanism and the same configuration as beacon+
See bellow a screenshot of the current state:
![image](https://user-images.githubusercontent.com/35198053/90228427-7f067d80-de16-11ea-9831-0b4ee351bc18.png)

I'm evaluating how I should structure the configuration files. If possible I would prevent duplicated configurations, and extend a base configuration for each use cases: beacon-plus and sample search.

My current understanding is the the current sample search seems to behave like the variantFusionRequest type. At least it works when selecting it.

Questions:

 - What are the request types for the sample search, in which order, and what is the default one?
 - How should it behave when having query parameters, for example when coming from the subsets selection?

**Comment by mbaudis** [comment]
As discussed, the request types are more of a demonstrator for Beacon than a requirement by the protocol. May evolve; but solved for current implementation through discussions. Closing.
