### ISSUE TITLE
Sample search: accessid

### ISSUE THREAD

**Issue by ptoussai** [progenetix/progenetix-web#27]
The accessid can be used to "aggregate" the current query with a former query's accessid.

However the beacon.py api does not seem to accept this parameter. It is also only returned in the handovers. Ideally it should be directly returned for further querying.

**Comment by mbaudis** [comment]
I'm on it. It is already implemented in the query execution library but I'll have to make it accepted as true query.

**Comment by mbaudis** [comment]
I guess this can be closed?
