### ISSUE TITLE
Biosubsets -> collations

### ISSUE THREAD

**Issue by mbaudis** [progenetix/progenetix-web#28]
The `api/?apidb=${datasetIds}&apiscope=biosubsets` calls could/should be replaced with calls against the new `collations` method:

* <https://next.progenetix.org/cgi/bycon/bin/collations.py?filters=NCIT&datasetIds=progenetix&method=counts>

... and similar. The methods can be found in the [**bycon** project](https://github.com/progenetix/bycon/blob/master/config/collations.yaml) itself.

**Comment by ptoussai** [comment]
This does not seems to work: https://next.progenetix.org/cgi/bycon/bin/collations.py?filters=NCIT&datasetIds=progenetix&method=paths

**Comment by mbaudis** [comment]
Fixed. the field for the paths was called as "paths", but it is "hierarchy_paths".

**Comment by ptoussai** [comment]
I did not implement it yet.
