### ISSUE TITLE
Fix site structure/reloads

### ISSUE THREAD

**Issue by mbaudis** [progenetix/progenetix-web#29]
The current mix of Apache & JS apps for leads to some errors e.g. when doing page reloads on other than the homepage.

**Comment by ptoussai** [comment]
In this case it seems to be completely specific to the "biosamples" name and some existing config.

**Comment by mbaudis** [comment]
Seems so ... But there isn't even `biosamples` anywhere in the Apache files... Maybe rename files/paths ... to "samples"?

**Comment by ptoussai** [comment]
Ok.

**Comment by mbaudis** [comment]
Works now (links against directories handled by Apache, not app -> protected...)
