### ISSUE TITLE
Implement samples search from publications

### ISSUE THREAD

**Issue by mbaudis** [progenetix/progenetix-web#32]
For the publications where there is data in progenetix | arraymap, a link should be created for executing a sample search 

Example dataset:

* <http://next.progenetix.org/publications/details?id=PMID:22824167&scope=datacollections> ("scope" isn't needed anymore, IMO)

The data query would then be

* <https://progenetix.org/cgi/bycon/bin/byconplus.py?datasetIds=progenetix,arraymap&filters=PMID:22824167&filterPrecision=exact>

(`filterPrecision=exact` is a new parameter to avoid the error-prone `$` regex terminations.)

**Comment by ptoussai** [comment]
Is filterPrecision=exact the default for all sample search or just that one?

**Comment by mbaudis** [comment]
This still has to be disentangled:

* default is start anchored regex, e.g. for just using the prefix w/o declaring a separate parameter
* if providing a list of specific filters => should use `filterPrecision=exact` now
* some URLs still use/demonstrate `$` terminated filters (e.g. PMID:123456$ somewhere...); such instances should be transformed

However: this is right now only in the `byconplus.py` methods; I'll add it to collations ... ASAP.
