### ISSUE TITLE
Add/improve JSON downloads

### ISSUE THREAD

**Issue by mbaudis** [progenetix/progenetix-web#33]
With the biosamples, variants ... data available through handover links it would be nice to enable data downloads. Some ideas:

* the biosamples / variants tabs could show a "Download data (JSON)" button; this could be changed to include other options (pop-up menu or such, e.g. for .csv data format)
* the current "Download JSON" should better open a new browser page w/ the JSON response; the download of the response isn't very useful, but the fast look at it might be. Could be less prominent, too (e.g. text link; I changed the label).
* the `data-visualization` page will provide file download options through links provided by the api_process method (since there is an option for random samples the handover id might be misleading since it points to the full set)

**Comment by ptoussai** [comment]
Implemented everything except for the  data-visualization
