### ISSUE TITLE
Organisation: Move project to progenetix

### ISSUE THREAD

**Issue by mbaudis** [progenetix/progenetix-web#35]
At some point the project should be moved to the progenetix organization. Set-up w/ vercel? Etc.

**Comment by ptoussai** [comment]
For Vercel, it's normally not free for (GitHub) organizations, but they could make exception open-source projects.
Vercel is not strictly required though. We can always decide later to use it if you think it's valuable.

**Comment by ptoussai** [comment]
Hello from the other side!

**Comment by mbaudis** [comment]
Hello 👍
