### ISSUE TITLE
Beacon "bio-ontologies" searches should include their child_terms

### ISSUE THREAD

**Issue by mbaudis** [progenetix/progenetix-web#38]
Searches using bio-ontologies (well, as"filters") should search on all the children of a selected term (as in the search from the subsets selection; "OR").

The `useFilteringTerms` now already requests the `child_terms` format of the response:

* `${basePath}cgi/bycon/bin/collations.py?method=children&responseFormat=simplelist&${params}`

**Comment by ptoussai** [comment]
@mbaudis: Could you check it out?

**Comment by mbaudis** [comment]
Doesn't work, I guess since w/o the OR value for `filterLogic`.

That is a bit of a conundrum since in principle there could than be other filters which we want as "and".

The clean way to do this would be to have the children derived at the backend, and totally to forget about them at the frontend ... This is something I'll have to do, I guess; but for now pls. just add the `filterLogic=OR` for this search type :-/

**Comment by ptoussai** [comment]
Can close this issue now ?
