### ISSUE TITLE
Beacon/Search: "examples" should only be displayed with a new search, and hidden/collapsed on existing (generated) pages.

### ISSUE THREAD

**Issue by ptoussai** [progenetix/progenetix-web#39]
This is from the issues-and-priorities.md. Could you specify what  existing (generated) means?
When coming from subsets, the whole form is collapsed already.

**Comment by mbaudis** [comment]
It is a bit much to have the examples displayed if not loading the search or Beacon page for the first time in a session. Cosmetic issue, though.

**Comment by ptoussai** [comment]
![image](https://user-images.githubusercontent.com/35198053/91995912-ab882800-ed38-11ea-8b12-e572236b8afe.png)
In this screenshot, are you talking about the "CNV Example" button?

**Comment by mbaudis** [comment]
Yes; there should better be an "Show Examples" Button (?) which doesn't take up vertical space if a user has engaged w. the site.

**Comment by ptoussai** [comment]
I'm not convinced it is worth it. Adding a is easy, but where? Also what defines a session in this case? 
What would be easy to do is to add the button to unfold the examples next to  Cytobands.
![image](https://user-images.githubusercontent.com/35198053/93097591-1117d500-f6a6-11ea-8f2c-f396b512c0dd.png)
