### ISSUE TITLE
Fix/modification: child_term selection now through backend

### ISSUE THREAD

**Issue by mbaudis** [progenetix/progenetix-web#42]
The API has been changed to default to "exact" matches retrieve all child terms for a selected term and treat them with "OR"

Not much tested but seems to work. Not yet on server, though. Therefore changes for sample searches are needed:

### Subsets
* only selected terms are used, not their child_terms
* filterLogic=OR (i.e., like now)

### Samples / Beacon:
* only selected terms are used, not their child_terms
* warning/highlight for "FilterLogic" selector

**Comment by ptoussai** [comment]
I did the changes, please check and close the issue.

**Comment by mbaudis** [comment]
Works now as expected. +1
