### ISSUE TITLE
Geodata: Display query results on a geographic map

### ISSUE THREAD

**Issue by mbaudis** [progenetix/progenetix-web#44]
Both for publications & sample searches it would be nice to have a display of the query results by geographic distribution, using e.g. marker size, density for showing the sum of items (or, in the case of publications, the sum of counts ...) w/ additional pop-ups (e.g. list of publications w/ links to their pages).

We have a simple version which shows the principle of this at <https://info.progenetix.org/pubmap.html>.

**Comment by ptoussai** [comment]
Added BiosamplesMap. Also found a way to render a data table inside the popup.
