### ISSUE TITLE
Feature: New Page - User uploads

### ISSUE THREAD

**Issue by mbaudis** [progenetix/progenetix-web#46]
(The) one main feature still missing compared to the old site is the "User File Visualization" option. This should get a version in the new site. The target would be the "data-visualization" page, with a file name as the submitted parameter (the data loader still has to be re-adjusted on the backend; testing can be done w/ the legacy version ...).

<https://info.progenetix.org/uploader.html>

**Comment by ptoussai** [comment]
Created the /data-visualization-upload page for testing purpose so you can adapt the server.

**Comment by ptoussai** [comment]
Could be closed?
