### ISSUE TITLE
Feature: Clickable help w/ panel

### ISSUE THREAD

**Issue by mbaudis** [progenetix/progenetix-web#48]
It would be good to provide help texts for the sample ... search forms, e.g. through a clickable indicator after the label, and then a panel showing the associated information (below the form fields?). Help text would be defined in `parameters.yaml`. (But same system would be good for plotting options & there parameters are inline ...)

**Comment by ptoussai** [comment]
I think the panel should be a tooltip. It would be otherwise much more complicated to find a good space for it.
What do you think? 

![image](https://user-images.githubusercontent.com/35198053/93090205-b3cb5600-f69c-11ea-86d3-30ba4c6ba5bd.png)

**Comment by ptoussai** [comment]
You can now set the infoText label. It support some markdown. Check freeFilters for an example.

**Comment by ptoussai** [comment]
InfoText props can also be set on the DataVisualizationPage.
I don't really see the need to extract that into a config, but it could be done.

**Comment by mbaudis** [comment]
O.k.; prefer it this way.
