### ISSUE TITLE
Fix: `useIsFilterlogicWarningVisible if` > 1 filter and "AND"

### ISSUE THREAD

**Issue by mbaudis** [progenetix/progenetix-web#49]
The current warning only evaluates `bioontology`; however, it should warn if >1 of parameters interpreted as `filters` (see e.g. the concatenation of `bioontology`, `materialtype`, `freeFilters` in `QuerySummary`).

**Comment by ptoussai** [comment]
Fixed, took the opportunity to cleanup some code and share it with the QuerySummary
