### ISSUE TITLE
Service page

### ISSUE THREAD

**Issue by mbaudis** [progenetix/progenetix-web#50]
As a side project from the data annotations we're now having a number of [services](https://github.com/progenetix/bycon/blob/master/doc/services.md) which do not directly address the main data collections but associated "helpers". For some of those it would be good to have dedicated web pages, usually providing some form fields w/ autocomplete/selection and a response area (single value or list/table).

Basic requirements:

* search field w/ autocomplete, multiple values
* aggregate search; e.g. a selected value is added to the autocomplete query for the next
  - example: searching ontologies => a selected icdom term limits the options for the 2nd select to all entries having this code, too
* templates for responses (table, single object)

**Comment by ptoussai** [comment]
I just added a page /services/ontologymaps.
