### ISSUE TITLE
Fix: Clean out sample search error message when initiating new search

### ISSUE THREAD

**Issue by mbaudis** [progenetix/progenetix-web#52]
Maybe only a problem during development, but error messages in search are persistent until the next response comes in; should be cleared when hitting the search button.

**Comment by ptoussai** [comment]
Could you give me the steps to reproduce this issue?

**Comment by mbaudis** [comment]
This was when getting an error from the API -> yellow box -> new search parameters w/ long load time -> yellow box persisted until (now correct) result came in.
