### ISSUE TITLE
Error: Missing subset labels

### ISSUE THREAD

**Issue by mbaudis** [progenetix/progenetix-web#59]
There is a strange problem w/ the hierarchies (subsets tree). Some of the high-level subsets only show the id in tree view, not the label. This seems to be the case for the first descending branch in NCIT and UBERON (?). 

Please see <https://progenetix.org/subsets/list?filters=NCIT> or <https://progenetix.org/subsets/list?filters=UBERON>, in contrast to <https://progenetix.org/subsets/list?filters=NCIT:C7062&datasetIds=progenetix>.

**Comment by ptoussai** [comment]
Fixed the issue. The commit will make you laugh. Sloppy coding and joys of untyped languages :)
