### ISSUE TITLE
Refinement: Adjust histoplot size

### ISSUE THREAD

**Issue by mbaudis** [progenetix/progenetix-web#6]
The histoplot has a default width of 800px, which doesn't match the panel size.

Suggestion: Improve the appearance by passing `&-size_plotimage_w_px={___available_width_px___}` with the fetch call.

The image itself is static & won't adjust to changing view size.)

**Comment by ptoussai** [comment]
Fixed.
The image size adjust automatically (throttled) when the container is resized. This is a property of react being reactive and easier to do than not.
