### ISSUE TITLE
Filter input interferes with cohort switch

### ISSUE THREAD

**Issue by qingyao** [progenetix/progenetix-web#66]
The SubsetsTree function needs a fix. It creates the following bug in the page "progenetix.org/subsets/cohorts/": After filtering the subset with typed keywords, switching the cohort from the dropdown menu above causes page to crash. 
This filter option is temporarily removed in commit "progenetix/progenetix-next@7a7156e", but the filter function is still needed after the bug fix.

**Comment by ptoussai** [comment]
Thanks for the report. I fixed the issue.
