### ISSUE TITLE
Change: Drop separate start, startMax & end, endMax

### ISSUE THREAD

**Issue by mbaudis** [progenetix/progenetix-web#8]
This had been started in https://github.com/ptoussai/progenetix-next/commit/6e9f0eac17b942296b50d67fbe774701e2dd06e6 but reverted (probably due to parallel work). To emphasize:

* `start` and `startMax` are just expressions for a `start` array w/ 1 or 2 values `[start, startMax]`. The backend just treats them as `start[0] - 1` and `start[-1]`; i.e. a single value of `101` becomes `[100,101]`; 2 values of `101` & `500` become `[100,500]`
* single input values are used for most purposes; the exception so far is the CNV request, where a start and end interval _should_ be given, though single values _could_ be used due to the interpolation above (a single base interval isn't very helpful there but not directly wrong); so rather a warning message

IMO the separate use of optionally 2 values for start and end is confusing & it would be better to provide them in a single field each as `20000001-21975098` etc. (in the current example), and to split. The query string anyway sends `start= 20000001&start= 21975098`.

(Other changes in the linked commit: `materialType` => `filters` ...)

**Comment by mbaudis** [comment]
I have implemented the value split & adjustment. However, query generation should become less "hard coded".

**Comment by ptoussai** [comment]
@mbaudis does b450e816987cfdfc39e4e6d5d66d849e7de1ddf5 solve the remaining issue?

**Comment by ptoussai** [comment]
I added some validation in this commit: 7c07c3ce843f59d5189e4ae2b7e089c589b4d7c3
The error message might now be accurate, could you check?

@mbaudis: please close the issue if this is OK.

**Comment by mbaudis** [comment]
Seems good from reading the changes, AFAIK.
