### ISSUE TITLE
Refinement: Cytoband and Gene selectors

### ISSUE THREAD

**Issue by mbaudis** [progenetix/progenetix-web#9]
The old Beacon+ interface had form fields `cytoinputField` and `geneinputField` which weren't for submitting form values but rather to trigger Ajax driven population of `start`, `referenceName` ... fields.

While these are very helpful to users, the original use in the form context was confusing. Here it would e.g. be nice to have such lookups implemented in a pop up, panel ... etc.

This is a refinement; it doesn't change the core functions.

**Comment by ptoussai** [comment]
Just pushed commits adding this feature.

I could not get the Cytoband API to work without jQuery so this is not working but will be easy to do as soon as the api is fixed.
Gene Spans works but the API does not return correct JSON (there are extra characters before and after).  I fix on the front end for now.

**Comment by ptoussai** [comment]
I also think the handling of the Gene span response is not really what you want, but this is details and can be adjusted.

**Comment by mbaudis** [comment]
Cytobands: e.g.
```
https://progenetix.org/services/cytomapper?assemblyId=GRCh38&cytoBands=8q2
```
=>
```
{
  "ChromosomeLocation": {
    "chr": "8",
    "end": "q24.3",
    "species": "taxonomy:9606",
    "start": "q21.11",
    "type": "ChromosomeLocation"
  },
  "assemblyId": "GRCh38",
  "chroBases": "8:72000000-145138636",
  "cytoBands": "8q21.11q24.3",
  "end": 145138636,
  "error": {},
  "referenceName": "8",
  "request": {
    "assemblyId": "GRCh38",
    "chr": "8",
    "cytoBands": "8q2",
    "end": null,
    "species": "taxonomy:9606",
    "start": "q2"
  },
  "size": 73138636,
  "start": 72000000
}
```
... where

* `referenceName` => idem
* `start`, `end` => idem

Input would be the `assemblyId` (works without for default GRCh38); and the cytoband from the field ...

The API for this implements a `callback` option; code for this is

```
    if "callback" in byc[ "form_data" ]:
        cgi_print_json_callback(byc["form_data"].getvalue("callback"), [cyto_response])
   else:
        cgi_print_json_response(cyto_response)
```
=>
```
1235456({"data":[{"request": {"assemblyId":  ...
```
